stamped: false
inputs:
  linear:
    x: axis_left_y
  angular:
    # Use L2 and R2 for rotation
    # z: axis_l2 - axis_r2
    # Use right horizontal stick for rotation
    y: -axis_right_y 
    z: axis_right_x
scales:
  linear:
    x: 2.5
  angular:
    y: 0.5
    z: 2.5
